# Backstage override configuration for your local development environment

Authentication:
  github:
    name: backstage_dev
    url:
      home: http://local:3000/
      fallback: http://localhost:7007/api/auth/github/handler/frame
