# Backstage override configuration for your local development environment

backend:
  database:
  # ...
auth:
  environment: development
  providers:
    github:
      development:
        clientId: b213e8cef6b436bcc39c
        clientSecret: 58761dc32c3c28446d4f8995f427ddd79815c1ba
